### ISSUE TITLE
Error in sourceCpp

### ISSUE THREAD

**Issue by qianchenxi119** [BatzoglouLabSU/SIMLR#19]
Hi, 

I am running large scale version of SIMLR on a 64 bit windows system, with the latest version of R and Rtools.
I have no problem creating .o file, however, it pops out error message afterwards. I am so confusing right now. I didn't make any changes on Makevars and Makevars.win files. I'll highly appreciate that if someone could help me tackle this problem.

Here is my error :

`C:/Users/cqian/Documents/SIMLR/src/tsne.o:tsne.cpp:(.text+0x1b8f): undefined reference to 'dgemm_'
collect2.exe: error: ld returned 1 exit status`

Thanks!

**Comment by danro9685** [comment]
Dear @qianchenxi119, 

I would suggest you to install SIMLR either with the install_github command or from Bioconductor so that you will not have to do that manually. 

I am quoting the guide here: 

**INSTALLING SIMLR R Bioconductor IMPLEMENTATION**

As mentioned, SIMLR is also hosted on Bioconductor at https://bioconductor.org/packages/release/bioc/html/SIMLR.html and can be installed as follow. To install the package directly from Bioconductor, run the following commands directly from R:

source("https://bioconductor.org/biocLite.R")

biocLite("SIMLR")

Moreover, it is also possible to install the Github version of SIMLR from R by using the R library devtools.

library(devtools)

install_github("BatzoglouLabSU/SIMLR", ref = 'master')

library(SIMLR)

or,

library(devtools)

install_github("BatzoglouLabSU/SIMLR", ref = 'development')

library(SIMLR)

We notice that on the "master" branch it is hosted the latest stable version of the code which is also available on Bioconductor on the stable repository. While on the "development" branch it is hosted the latest version that is on the devel repository on Bioconductor. 

Best, 
Daniele
