### ISSUE TITLE
 Error: cannot allocate vector of size 7.7 Gb 

### ISSUE THREAD

**Issue by xuebaliang** [BatzoglouLabSU/SIMLR#45]
hello, I want to use SIMLR to cluster my single cell dataset with 32061 samples. But it seems to SIMLR can not deal with it. What can I do? Thanks!

error message:
[1] "end the preprocessing"
[1]    32 32061
[1] "begin SIMLR cluster"
Performing fast PCA.
Performing k-nearest neighbour search.
Computing the multiple Kernels.
 Show Traceback
 
 Rerun with Debug
 Error: cannot allocate vector of size 7.7 Gb

**Comment by danro9685** [comment]
Dear @xuebaliang, 

it seems that your error is occurring when Kernels are allocated into memory. 
This is the most memory (RAM) critical part of SIMLR. 
An option here is to increase your RAM (I see the error is at 7.7 Gb, can you allocate more?). 
If this is not feasible, you can either try to reduce the dimension of pca or to rewrite the Kernel computation part in order to save data to disk instead of RAM. 

Best, 
Daniele
