### ISSUE TITLE
Error in detectCores() : could not find function "detectCores"

### ISSUE THREAD

**Issue by TangYiChing** [BatzoglouLabSU/SIMLR#49]
Hello,

I was trying to run the multiple.kernel function without using the SIMLR function (see code below), and got the error message saying there is no detectCores function.

        **D_Kernels = multiple.kernel(t(BuettnerFlorian$in_X),cores.ratio)**

what would you recommend if I were to get a similarity matrix only, instead of doing clustering?

**Comment by danro9685** [comment]
Dear @TangYiChing, 

you would need to get the similarity matrix at the last step of SIMLR execution. This is returned by the function SIMLR as variable S. The clustering is the very last step and is not very time consuming. 

I would run the whole function instead of re-writing it. 

Best, 
Daniele
